name: windows_build_test

on:
  push:
    branches:
      - master  # 触发推送到 main 分支的事件，可以根据实际情况修改

jobs:
  build:
    name: Build And Test
    runs-on: windows-latest  # 使用 Windows 作为构建环境

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # 检出仓库代码

    - name: Create Build Directory
      run: mkdir build  # 创建 build 目录

    - name: Configure CMake
      # 进入 build 目录并执行 CMake 配置
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 ..

    - name: Build
      run: cmake --build build --config Release  --target ALL_BUILD # 使用构建系统编译项目

    - name: Run Tests (if applicable)
      run: cd build && ctest  # 运行测试（如果你的项目有测试）